In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv('Anime.csv')



In [16]:

df['my_score'] = pd.to_numeric(df['my_score'], errors='coerce')
df['score'] = pd.to_numeric(df['score'], errors='coerce')
df['popularity'] = pd.to_numeric(df['popularity'], errors='coerce')
df['Completed'] = pd.to_numeric(df['Completed'], errors='coerce')
df['scored_by'] = pd.to_numeric(df['scored_by'], errors='coerce')
# Handling missing values
df = df.dropna(subset=['my_score', 'score','scored_by','Completed', 'popularity'])  # Remove rows with missing values



In [25]:

# Separate the features (X) and the labels (y)
X = df.drop(['username', 'gender', 'title', 'type', 'source', 'genre','Duration','anime_id', 'user_id','popularity','Members','Favorites','On-Hold','Dropped','Completed','scored_by','Rating','rank'], axis=1)
y = df[['Completed']]
y = y.values.ravel()

In [26]:
#Split the dataset into training and testing sets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [27]:
import numpy as np

# Extract unique classes from y
classes = np.unique(y)

# Initialize the classifier
sgd_classifier = SGDClassifier()

# First call to partial_fit with classes argument
sgd_classifier.partial_fit(X_train, y_train, classes=classes)

# Subsequent calls to partial_fit without classes argument
sgd_classifier.partial_fit(X_train, y_train)

# Predict the labels for the test data
y_pred = sgd_classifier.predict(X_test)

# Initialize the RandomForestClassifier
rf_classifier = RandomForestClassifier()

# Fit the model on the training data
rf_classifier.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = rf_classifier.predict(X_test)


In [28]:
#Evaluate the accuracy of the model:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.2971602434077079


In [29]:
# Calculate the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[  0   0   1   3   2   7]
 [  0   0   0   2   1   4]
 [  0   0   3  24  15  48]
 [  1   4  13  99  59 158]
 [  2   3  16  47  21  72]
 [  3   2  18 149  39 170]]


In [30]:
# Perform cross-validation
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(rf_classifier, X, y, cv=5)
print("Cross-Validation Scores:", cv_scores)

Cross-Validation Scores: [0.32860041 0.32251521 0.31034483 0.29310345 0.29513185]
